// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/andreis3/customers-ms/internal/infra/commons/logger"
	"github.com/andreis3/customers-ms/internal/infra/configs"
	"github.com/andreis3/customers-ms/internal/infra/server"
)

// Injectors from wire.go:

func InitializeServer(conf *configs.Configs) *server.Server {
	loggerLogger := logger.NewLogger()
	serverServer := server.NewServer(conf, loggerLogger)
	return serverServer
}
