server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: system

scrape_configs:
  - job_name: myapps
    static_configs:
      - targets:
          - localhost
        labels:
          job: myapp
          __path__: /var/log/app/*.log

    pipeline_stages:
      - json:
          expressions:
            trace_id: trace_id
            span_id: span_id
            level: level
            msg: msg
            path: path

      - labels:
          trace_id: ""
          span_id: ""
          level: ""
          path: ""
