global:
  scrape_interval: "5s"
  scrape_timeout: "5s"
  evaluation_interval: "5s"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1s
  - job_name: "foodtosave-case"
    scrape_interval: 1s
    static_configs:
      - targets: ["localhost:8080", "localhost:8081"]
